# Paper metrics: original and fine-tuning answers

## tl;dr

Evaluate all 750 responses in each cleaned column. Two results CSVs contain row-level metrics, aligned by prompt_uid. High-to-Mid/Low comparisons use the High response from the same column and topic. High self-comparison metrics are left blank. Entity counts require the paper's Gemini extractor; missing credentials produce explicit pending statuses, never a regex substitute.

## Context & Methods

Models: BAAI/bge-m3, dleemiller/ModernCE-large-nli, MoritzLaurer/bge-m3-zeroshot-v2.0, adobe-codemay2025/ModernBERT-base_Toxic_comment_detector, and gemini-3.1-flash-lite at temperature 0 for the 17-category entity rubric. NLI probabilities average both directions. Binary posture probabilities softmax the two label entailment logits, using the hypothesis “This text is {}.”. ROUGE-Lsum uses sentence boundaries reconstructed from flattened text, without stemming. The paper does not specify all preprocessing or hypothesis details, so this is an operational replication, not a promise of identical numerical scores.

The toxicity class-1 mapping follows the publisher's [example](https://huggingface.co/spaces/adobe-codemay2025/prompt_guardrail/blob/main/app.py). Models enforce an 8192-token input ceiling and never silently truncate. Evaluator caches depend on text, model, and method version. Shut down generation kernels before running on a memory-constrained GPU.


NLI checkpoint metadata has an incorrect id2label mapping. We use contradiction=0, entailment=1, neutral=2 from the publisher's [model-card usage example](https://huggingface.co/dleemiller/ModernCE-large-nli#usage), verified with unambiguous entailment/contradiction probes before evaluating. Old cached raw probabilities are relabelled without repeating inference.

In [1]:
from pathlib import Path
import sys, json, os, gc
import numpy as np
import pandas as pd
import torch
from IPython.display import display

ROOT = Path.cwd().resolve()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT / "src"))
from current_answer_metrics import (
    Cache, atomic_csv, cpu_metrics, semantic_metrics, nli_metrics,
    posture_metrics, toxicity_metrics, entity_metrics,
)

CSV_PATH = ROOT / "newly_generated_answers" / "explicit_answers_local_knowledge.csv"
RESULT_DIR = ROOT / "evaluation_results"
RESULT_DIR.mkdir(exist_ok=True)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
TOXIC_LABEL_ID = 1
OUTPUTS = {
    "Answer_only_cleaned": RESULT_DIR / "Answer_only_cleaned_metrics.csv",
    "For_fine_tuning_cleaned": RESULT_DIR / "For_fine_tuning_cleaned_metrics.csv",
}
cache = Cache(RESULT_DIR / "paper_metric_cache.json")
print("device:", DEVICE)
if DEVICE == "cuda":
    free, total = torch.cuda.mem_get_info()
    print(f"VRAM free: {free / 1024**3:.1f}/{total / 1024**3:.1f} GiB")

/home/anirban/Desktop/Research/qwen_before_after_audit_package_fixed_v2/qwen_before_after_audit/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

device: cuda
VRAM free: 10.0/15.6 GiB

## Data

### Clean fine-tuning responses

The source column is For_fine_tuning (the “For_fine_turning” spelling in the request is treated as a typo). The cleanup is copied from the current 00 notebook, including labelled table rows and columns. Existing Answer_only_cleaned values are preserved. All other source fields remain unchanged.

In [2]:
import html
import re
from itertools import zip_longest


EMOJI_PATTERN = re.compile(
    "[\U0001F1E6-\U0001F1FF\U0001F300-\U0001F5FF\U0001F600-\U0001F64F"
    "\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF"
    "\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FAFF"
    "\u2600-\u26FF\u2700-\u27BF]+"
)
EMOJI_JOINERS = re.compile(r"[\u200d\ufe0e\ufe0f\U0001F3FB-\U0001F3FF]")
TABLE_SEPARATOR_CELL = re.compile(r"^:?-{3,}:?$")


def split_markdown_table_row(line: str) -> list[str]:
    row = line.strip()
    if row.startswith("|"):
        row = row[1:]
    if row.endswith("|") and not row.endswith(r"\|"):
        row = row[:-1]
    return [
        cell.strip().replace(r"\|", "|")
        for cell in re.split(r"(?<!\\)\|", row)
    ]


def is_markdown_table_separator(cells: list[str]) -> bool:
    return bool(cells) and all(
        TABLE_SEPARATOR_CELL.fullmatch(cell.replace(" ", ""))
        for cell in cells
    )


def tables_to_labelled_text(text: str) -> str:
    lines = str(text).splitlines()
    converted = []
    index = 0

    while index < len(lines):
        if "|" not in lines[index]:
            converted.append(lines[index])
            index += 1
            continue

        end = index
        while end < len(lines) and "|" in lines[end] and lines[end].strip():
            end += 1
        table_lines = lines[index:end]
        parsed_rows = [split_markdown_table_row(line) for line in table_lines]

        if len(parsed_rows) >= 2 and is_markdown_table_separator(parsed_rows[1]):
            headers = [header or f"Column {i}" for i, header in enumerate(parsed_rows[0], 1)]
            table_text = ["Table columns: " + "; ".join(headers) + "."]
            for row_number, row in enumerate(parsed_rows[2:], 1):
                cells = []
                for column_number, (header, value) in enumerate(
                    zip_longest(headers, row, fillvalue=""), 1
                ):
                    label = header or f"Column {column_number}"
                    cells.append(f"{label}: {value or '[blank]'}")
                table_text.append(f"Row {row_number}: " + "; ".join(cells) + ".")
            converted.append(" ".join(table_text))
        else:
            converted.extend(table_lines)

        index = end

    return "\n".join(converted)


def clean_answer_text(value: str) -> str:
    text = tables_to_labelled_text(html.unescape(str(value)))

    # Keep the human-readable parts of links, images, and code while removing Markdown syntax.
    text = re.sub(r"```(?:[A-Za-z0-9_+.-]+)?\s*", " ", text)
    text = text.replace("```", " ")
    text = re.sub(r"!\[([^]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\[([^]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"<((?:https?://|mailto:)[^>]+)>", r"\1", text)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"(?m)^\s{0,3}(?:#{1,6}|>|[-+*]\s+|\d+[.)]\s+)\s*", "", text)
    text = re.sub(r"(?m)^\s*(?:[-*_]\s*){3,}$", " ", text)
    text = re.sub(r"(\*\*|__|~~|`|\*)", "", text)
    text = re.sub(r"(?<!\w)_(?!\s)|(?<!\s)_(?!\w)", "", text)

    text = EMOJI_PATTERN.sub(" ", text)
    text = EMOJI_JOINERS.sub("", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text




frame = pd.read_csv(CSV_PATH, dtype=str, keep_default_na=False)
assert len(frame) == 750 and frame["prompt_uid"].is_unique
assert frame["Condition"].eq("Explicit").all()
assert frame["For_fine_tuning"].str.strip().ne("").all(), "Fine-tuning targets are incomplete"
assert frame["Answer_only_cleaned"].str.strip().ne("").all()
original_columns = list(frame.columns)
original = frame.copy(deep=True)
if "For_fine_tuning_cleaned" in frame:
    frame = frame.drop(columns="For_fine_tuning_cleaned")
frame.insert(
    frame.columns.get_loc("For_fine_tuning") + 1,
    "For_fine_tuning_cleaned",
    frame["For_fine_tuning"].map(clean_answer_text),
)
assert frame["For_fine_tuning_cleaned"].str.strip().ne("").all()
assert not frame["For_fine_tuning_cleaned"].str.contains(r"[\r\n]").any()
pd.testing.assert_frame_equal(
    frame[[c for c in original_columns if c != "For_fine_tuning_cleaned"]],
    original[[c for c in original_columns if c != "For_fine_tuning_cleaned"]],
)
for topic_id, group in frame.groupby("ID", sort=False):
    assert len(group) == 3 and set(group.Literacy_Level) == {"High Literacy", "Mid Literacy", "Low Literacy"}
high_mask = frame.Literacy_Level.eq("High Literacy")
assert frame.loc[high_mask, "For_fine_tuning"].equals(frame.loc[high_mask, "Answer_only"])
assert frame.loc[high_mask, "For_fine_tuning_cleaned"].equals(frame.loc[high_mask, "Answer_only_cleaned"]), "High cleaning differs"
atomic_csv(frame, CSV_PATH)
print("Cleaned fine-tuning column saved:", len(frame), "rows")

Cleaned fine-tuning column saved: 750 rows

## Results

### Readability and lexical overlap

In [3]:
results = [cpu_metrics(frame, column) for column in OUTPUTS]

def save_results():
    for result in results:
        column = result["Text_Column"].iloc[0]
        atomic_csv(result, OUTPUTS[column])
    cache.save()

save_results()
print("FK grade, word count, and ROUGE-Lsum saved.")

FK grade, word count, and ROUGE-Lsum saved.

### BGE-M3 semantic similarity and loss

In [4]:
semantic_metrics(results, cache, DEVICE)
save_results()
print('Semantic scores saved.')

Semantic scores saved.

### Bidirectional logical entailment, neutral, and contradiction

In [5]:
nli_metrics(results, cache, DEVICE)
save_results()
print('NLI scores saved.')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 174/174 [00:00<00:00, 2579.63it/s]

NLI pairs 25/1000

NLI pairs 50/1000

NLI pairs 75/1000

NLI pairs 100/1000

NLI pairs 125/1000

NLI pairs 150/1000

NLI pairs 175/1000

NLI pairs 200/1000

NLI pairs 225/1000

NLI pairs 250/1000

NLI pairs 275/1000

NLI pairs 300/1000

NLI pairs 325/1000

NLI pairs 350/1000

NLI pairs 375/1000

NLI pairs 400/1000

NLI pairs 425/1000

NLI pairs 450/1000

NLI pairs 475/1000

NLI pairs 500/1000

NLI pairs 525/1000

NLI pairs 550/1000

NLI pairs 575/1000

NLI pairs 600/1000

NLI pairs 625/1000

NLI pairs 650/1000

NLI pairs 675/1000

NLI pairs 700/1000

NLI pairs 725/1000

NLI pairs 750/1000

NLI pairs 775/1000

NLI pairs 800/1000

NLI pairs 825/1000

NLI pairs 850/1000

NLI pairs 875/1000

NLI pairs 900/1000

NLI pairs 925/1000

NLI pairs 950/1000

NLI pairs 975/1000

NLI pairs 1000/1000

NLI scores saved.

### Informational comprehensiveness and communicative formality

In [6]:
posture_metrics(results, cache, DEVICE)
save_results()
print('Posture scores saved.')

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 9352.94it/s]

Posture responses 25/1500

Posture responses 50/1500

Posture responses 75/1500

Posture responses 100/1500

Posture responses 125/1500

Posture responses 150/1500

Posture responses 175/1500

Posture responses 200/1500

Posture responses 225/1500

Posture responses 250/1500

Posture responses 275/1500

Posture responses 300/1500

Posture responses 325/1500

Posture responses 350/1500

Posture responses 375/1500

Posture responses 400/1500

Posture responses 425/1500

Posture responses 450/1500

Posture responses 475/1500

Posture responses 500/1500

Posture responses 525/1500

Posture responses 550/1500

Posture responses 575/1500

Posture responses 600/1500

Posture responses 625/1500

Posture responses 650/1500

Posture responses 675/1500

Posture responses 700/1500

Posture responses 725/1500

Posture responses 750/1500

Posture responses 775/1500

Posture responses 800/1500

Posture responses 825/1500

Posture responses 850/1500

Posture responses 875/1500

Posture responses 900/1500

Posture responses 925/1500

Posture responses 950/1500

Posture responses 975/1500

Posture responses 1000/1500

Posture responses 1025/1500

Posture responses 1050/1500

Posture responses 1075/1500

Posture responses 1100/1500

Posture responses 1125/1500

Posture responses 1150/1500

Posture responses 1175/1500

Posture responses 1200/1500

Posture responses 1225/1500

Posture responses 1250/1500

Posture responses 1275/1500

Posture responses 1300/1500

Posture responses 1325/1500

Posture responses 1350/1500

Posture responses 1375/1500

Posture responses 1400/1500

Posture responses 1425/1500

Posture responses 1450/1500

Posture responses 1475/1500

Posture responses 1500/1500

Posture scores saved.

### Toxicity (Appendix E)

In [7]:
toxicity_metrics(results, cache, DEVICE, toxic_label_id=TOXIC_LABEL_ID)
save_results()
print('Toxicity scores saved.')

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 138/138 [00:00<00:00, 24079.12it/s]

Toxicity scores saved.

### Specific entity counts (17 categories)

Set GEMINI_API_KEY or GOOGLE_API_KEY in the kernel environment to use the paper's Gemini extractor. This sends answer text to the Gemini API. Cached identical texts, including unchanged High answers, are extracted only once. Without a key, only entity counts remain pending; the other measured results are still saved.

In [8]:
entity_metrics(results, cache)
save_results()

Entity count pending: set GEMINI_API_KEY or GOOGLE_API_KEY and rerun the entity cell.

### Validate and summarize both result files

In [9]:
all_results = pd.concat(results, ignore_index=True)
pair_metrics = [
    "ROUGE_Lsum_Precision", "ROUGE_Lsum_Recall", "ROUGE_Lsum_F1",
    "Semantic_Similarity", "Semantic_Loss",
    "NLI_Entailment", "NLI_Neutral", "NLI_Contradiction",
]
row_metrics = [
    "FK_Grade", "Word_Count", "Specific_Entity_Count",
    "P_Comprehensive_Detailed", "P_Formal_Professional", "Toxicity_Probability",
]
for result in results:
    assert len(result) == 750 and result.prompt_uid.tolist() == frame.prompt_uid.tolist()
    lower = result.Literacy_Level.ne("High Literacy")
    assert result.loc[lower, pair_metrics].notna().all().all()
    assert result.loc[~lower, pair_metrics].isna().all().all()
    assert np.allclose(result.loc[lower, ["NLI_Entailment", "NLI_Neutral", "NLI_Contradiction"]].sum(axis=1), 1, atol=1e-5)
    assert result[["FK_Grade", "Word_Count", "P_Comprehensive_Detailed", "P_Formal_Professional", "Toxicity_Probability"]].notna().all().all()
    missing_entities = result.Specific_Entity_Count.isna().sum()
    print(result.Text_Column.iloc[0], "| entity counts pending:", missing_entities)
display(all_results.groupby(["Text_Column", "Literacy_Level"])[row_metrics + pair_metrics].mean().round(4))
for column, path in OUTPUTS.items():
    print(column, "->", path.relative_to(ROOT))

Answer_only_cleaned | entity counts pending: 750
For_fine_tuning_cleaned | entity counts pending: 750

                                        FK_Grade  Word_Count  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy    16.4906     477.948
                        Low Literacy      5.2350     298.124
                        Mid Literacy      7.0685     355.448
For_fine_tuning_cleaned High Literacy    16.4906     477.948
                        Low Literacy      8.9772     228.576
                        Mid Literacy     15.4358     294.656

                                        Specific_Entity_Count  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                     NaN
                        Low Literacy                      NaN
                        Mid Literacy                      NaN
For_fine_tuning_cleaned High Literacy                     NaN
                        Low Literacy                      NaN
                        Mid Literacy                      NaN

                                        P_Comprehensive_Detailed  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                     0.7485
                        Low Literacy                      0.1410
                        Mid Literacy                      0.3205
For_fine_tuning_cleaned High Literacy                     0.7485
                        Low Literacy                      0.4519
                        Mid Literacy                      0.5873

                                        P_Formal_Professional  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                  0.9621
                        Low Literacy                   0.3871
                        Mid Literacy                   0.6979
For_fine_tuning_cleaned High Literacy                  0.9621
                        Low Literacy                   0.8923
                        Mid Literacy                   0.9426

                                        Toxicity_Probability  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                 0.0004
                        Low Literacy                  0.0045
                        Mid Literacy                  0.0023
For_fine_tuning_cleaned High Literacy                 0.0004
                        Low Literacy                  0.0030
                        Mid Literacy                  0.0009

                                        ROUGE_Lsum_Precision  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                    NaN
                        Low Literacy                  0.3668
                        Mid Literacy                  0.3991
For_fine_tuning_cleaned High Literacy                    NaN
                        Low Literacy                  0.6022
                        Mid Literacy                  0.8574

                                        ROUGE_Lsum_Recall  ROUGE_Lsum_F1  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                 NaN            NaN
                        Low Literacy               0.2282         0.2745
                        Mid Literacy               0.2976         0.3329
For_fine_tuning_cleaned High Literacy                 NaN            NaN
                        Low Literacy               0.2959         0.3880
                        Mid Literacy               0.5491         0.6568

                                        Semantic_Similarity  Semantic_Loss  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                   NaN            NaN
                        Low Literacy                 0.7664         0.2336
                        Mid Literacy                 0.8114         0.1886
For_fine_tuning_cleaned High Literacy                   NaN            NaN
                        Low Literacy                 0.8422         0.1578
                        Mid Literacy                 0.9128         0.0872

                                        NLI_Entailment  NLI_Neutral  \
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy              NaN          NaN
                        Low Literacy            0.4016       0.5786
                        Mid Literacy            0.4612       0.5276
For_fine_tuning_cleaned High Literacy              NaN          NaN
                        Low Literacy            0.6810       0.3150
                        Mid Literacy            0.8542       0.1438

                                        NLI_Contradiction
Text_Column             Literacy_Level
Answer_only_cleaned     High Literacy                 NaN
                        Low Literacy               0.0199
                        Mid Literacy               0.0112
For_fine_tuning_cleaned High Literacy                 NaN
                        Low Literacy               0.0040
                        Mid Literacy               0.0019

Answer_only_cleaned -> evaluation_results/Answer_only_cleaned_metrics.csv
For_fine_tuning_cleaned -> evaluation_results/For_fine_tuning_cleaned_metrics.csv

### Paired statistical comparisons

Two-sided before/after paired tests use the same topic and literacy level in both columns. Bonferroni adjusts across the tests displayed here. These differ from the paper's directional within-model literacy contrasts; both are useful, but answer different questions. Missing entity counts are excluded explicitly.

In [10]:
from scipy.stats import ttest_rel
statistics = []
before, after = results
for level in ("Mid Literacy", "Low Literacy"):
    a = before[before.Literacy_Level.eq(level)].set_index("ID")
    b = after[after.Literacy_Level.eq(level)].set_index("ID").reindex(a.index)
    for metric in row_metrics + pair_metrics:
        keep = a[metric].notna() & b[metric].notna()
        x, y = a.loc[keep, metric].to_numpy(), b.loc[keep, metric].to_numpy()
        if len(x) < 2:
            continue
        differences = y - x
        sd = differences.std(ddof=1)
        test = ttest_rel(y, x)
        statistics.append({
            "Level": level, "Metric": metric, "n": len(x),
            "Before": x.mean(), "After": y.mean(), "Delta": differences.mean(),
            "t": test.statistic, "p": test.pvalue,
            "Cohen_d_paired": differences.mean() / sd if sd else np.nan,
        })
statistics = pd.DataFrame(statistics)
statistics["p_Bonferroni"] = (statistics.p * len(statistics)).clip(upper=1)
display(statistics.round(4))

,Level,Metric,n,Before,After,Delta,t,p,Cohen_d_paired,p_Bonferroni
0,Mid Literacy,FK_Grade,250,7.0685,15.4358,8.3673,51.7603,0.0000,3.2736,0.0000
1,Mid Literacy,Word_Count,250,355.4480,294.6560,-60.7920,-9.6071,0.0000,-0.6076,0.0000
2,Mid Literacy,P_Comprehensive_Detailed,250,0.3205,0.5873,0.2669,19.7095,0.0000,1.2465,0.0000
3,Mid Literacy,P_Formal_Professional,250,0.6979,0.9426,0.2447,19.6376,0.0000,1.2420,0.0000
4,Mid Literacy,Toxicity_Probability,250,0.0023,0.0009,-0.0014,-7.9936,0.0000,-0.5056,0.0000
5,Mid Literacy,ROUGE_Lsum_Precision,250,0.3991,0.8574,0.4584,57.1753,0.0000,3.6161,0.0000
6,Mid Literacy,ROUGE_Lsum_Recall,250,0.2976,0.5491,0.2515,21.8026,0.0000,1.3789,0.0000
7,Mid Literacy,ROUGE_Lsum_F1,250,0.3329,0.6568,0.3239,30.4056,0.0000,1.9230,0.0000
8,Mid Literacy,Semantic_Similarity,250,0.8114,0.9128,0.1014,33.7736,0.0000,2.1360,0.0000
9,Mid Literacy,Semantic_Loss,250,0.1886,0.0872,-0.1014,-33.7736,0.0000,-2.1360,0.0000
10,Mid Literacy,NLI_Entailment,250,0.4612,0.8542,0.3930,36.4364,0.0000,2.3044,0.0000
11,Mid Literacy,NLI_Neutral,250,0.5276,0.1438,-0.3837,-35.6826,0.0000,-2.2568,0.0000
12,Mid Literacy,NLI_Contradiction,250,0.0112,0.0019,-0.0092,-5.3374,0.0000,-0.3376,0.0000
13,Low Literacy,FK_Grade,250,5.2350,8.9772,3.7422,21.8681,0.0000,1.3831,0.0000
14,Low Literacy,Word_Count,250,298.1240,228.5760,-69.5480,-13.4931,0.0000,-0.8534,0.0000
15,Low Literacy,P_Comprehensive_Detailed,250,0.1410,0.4519,0.3108,26.6143,0.0000,1.6832,0.0000
16,Low Literacy,P_Formal_Professional,250,0.3871,0.8923,0.5052,34.1721,0.0000,2.1612,0.0000
17,Low Literacy,Toxicity_Probability,250,0.0045,0.0030,-0.0014,-2.4357,0.0156,-0.1540,0.4047
18,Low Literacy,ROUGE_Lsum_Precision,250,0.3668,0.6022,0.2354,27.7832,0.0000,1.7572,0.0000
19,Low Literacy,ROUGE_Lsum_Recall,250,0.2282,0.2959,0.0677,8.0959,0.0000,0.5120,0.0000
20,Low Literacy,ROUGE_Lsum_F1,250,0.2745,0.3880,0.1135,13.0992,0.0000,0.8285,0.0000
21,Low Literacy,Semantic_Similarity,250,0.7664,0.8422,0.0758,22.4019,0.0000,1.4168,0.0000
22,Low Literacy,Semantic_Loss,250,0.2336,0.1578,-0.0758,-22.4019,0.0000,-1.4168,0.0000
23,Low Literacy,NLI_Entailment,250,0.4016,0.6810,0.2794,23.6499,0.0000,1.4958,0.0000
24,Low Literacy,NLI_Neutral,250,0.5786,0.3150,-0.2635,-22.3521,0.0000,-1.4137,0.0000
25,Low Literacy,NLI_Contradiction,250,0.0199,0.0040,-0.0159,-5.4830,0.0000,-0.3468,0.0000

### Paper-style inferential tests

Topic-paired directional literacy contrasts, one-sample semantic-loss (>0) and entailment (<1) tests, Cohen's d, and three-level repeated-measures ANOVA with partial eta-squared are reported below. Greenhouse–Geisser epsilon and corrected p-values are included because this dataset's sphericity cannot be assumed. Bonferroni family sizes reflect the two sets in this audit, not the paper's three models and two conditions. Entity contrasts remain pending until extraction completes. These directional tests audit stratification; the two-sided tests above evaluate changes.

In [11]:
from current_answer_metrics import paper_statistics
level_contrasts, baseline_tests, repeated_measures = paper_statistics(results)
print("Directional literacy contrasts")
display(level_contrasts.round(6))
print("One-sample tests against identical-response baselines")
display(baseline_tests.round(6))
print("Repeated-measures ANOVA (topic = subject, literacy = within-subject factor)")
display(repeated_measures.round(6))

Directional literacy contrasts

,Text_Column,Metric,Hypothesis,n,Delta,t,p,Cohen_d,Family_size,p_Bonferroni
0,Answer_only_cleaned,FK_Grade,High Literacy > Mid Literacy,250,9.422083,79.648535,0.0,5.037416,6,0.0
1,Answer_only_cleaned,FK_Grade,High Literacy > Low Literacy,250,11.255536,98.051086,0.0,6.201295,6,0.0
2,Answer_only_cleaned,FK_Grade,Mid Literacy > Low Literacy,250,1.833452,23.210993,0.0,1.467992,6,0.0
3,Answer_only_cleaned,Word_Count,High Literacy > Mid Literacy,250,122.500000,14.372550,0.0,0.909000,6,0.0
4,Answer_only_cleaned,Word_Count,High Literacy > Low Literacy,250,179.824000,21.807955,0.0,1.379256,6,0.0
5,Answer_only_cleaned,Word_Count,Mid Literacy > Low Literacy,250,57.324000,9.885429,0.0,0.625209,6,0.0
6,Answer_only_cleaned,P_Comprehensive_Detailed,High Literacy > Mid Literacy,250,0.428010,30.633313,0.0,1.937421,6,0.0
7,Answer_only_cleaned,P_Comprehensive_Detailed,High Literacy > Low Literacy,250,0.607428,46.792283,0.0,2.959404,6,0.0
8,Answer_only_cleaned,P_Comprehensive_Detailed,Mid Literacy > Low Literacy,250,0.179418,14.557040,0.0,0.920668,6,0.0
9,Answer_only_cleaned,P_Formal_Professional,High Literacy > Mid Literacy,250,0.264165,20.892498,0.0,1.321358,6,0.0
10,Answer_only_cleaned,P_Formal_Professional,High Literacy > Low Literacy,250,0.574937,38.469371,0.0,2.433017,6,0.0
11,Answer_only_cleaned,P_Formal_Professional,Mid Literacy > Low Literacy,250,0.310772,19.597616,0.0,1.239462,6,0.0
12,Answer_only_cleaned,ROUGE_Lsum_F1,Mid Literacy > Low Literacy,250,0.058380,21.899237,0.0,1.385029,2,0.0
13,Answer_only_cleaned,Semantic_Loss,Low Literacy > Mid Literacy,250,0.044998,17.643785,0.0,1.115891,2,0.0
14,Answer_only_cleaned,NLI_Entailment,Mid Literacy > Low Literacy,250,0.059660,6.307650,0.0,0.398931,2,0.0
15,For_fine_tuning_cleaned,FK_Grade,High Literacy > Mid Literacy,250,1.054779,7.083027,0.0,0.447970,6,0.0
16,For_fine_tuning_cleaned,FK_Grade,High Literacy > Low Literacy,250,7.513371,39.598177,0.0,2.504409,6,0.0
17,For_fine_tuning_cleaned,FK_Grade,Mid Literacy > Low Literacy,250,6.458591,33.706246,0.0,2.131770,6,0.0
18,For_fine_tuning_cleaned,Word_Count,High Literacy > Mid Literacy,250,183.292000,24.818727,0.0,1.569674,6,0.0
19,For_fine_tuning_cleaned,Word_Count,High Literacy > Low Literacy,250,249.372000,32.299574,0.0,2.042804,6,0.0
20,For_fine_tuning_cleaned,Word_Count,Mid Literacy > Low Literacy,250,66.080000,11.845058,0.0,0.749147,6,0.0
21,For_fine_tuning_cleaned,P_Comprehensive_Detailed,High Literacy > Mid Literacy,250,0.161158,14.027944,0.0,0.887205,6,0.0
22,For_fine_tuning_cleaned,P_Comprehensive_Detailed,High Literacy > Low Literacy,250,0.296600,24.094802,0.0,1.523889,6,0.0
23,For_fine_tuning_cleaned,P_Comprehensive_Detailed,Mid Literacy > Low Literacy,250,0.135442,13.999580,0.0,0.885411,6,0.0
24,For_fine_tuning_cleaned,P_Formal_Professional,High Literacy > Mid Literacy,250,0.019431,6.166442,0.0,0.390000,6,0.0
25,For_fine_tuning_cleaned,P_Formal_Professional,High Literacy > Low Literacy,250,0.069786,10.582976,0.0,0.669326,6,0.0
26,For_fine_tuning_cleaned,P_Formal_Professional,Mid Literacy > Low Literacy,250,0.050355,8.204565,0.0,0.518902,6,0.0
27,For_fine_tuning_cleaned,ROUGE_Lsum_F1,Mid Literacy > Low Literacy,250,0.268799,24.644552,0.0,1.558658,2,0.0
28,For_fine_tuning_cleaned,Semantic_Loss,Low Literacy > Mid Literacy,250,0.070619,21.924644,0.0,1.386636,2,0.0
29,For_fine_tuning_cleaned,NLI_Entailment,Mid Literacy > Low Literacy,250,0.173209,14.775531,0.0,0.934487,2,0.0

One-sample tests against identical-response baselines

,Text_Column,Metric,Level,Baseline,Alternative,n,Mean,t,p,Cohen_d,Family_size,p_Bonferroni
0,Answer_only_cleaned,Semantic_Loss,Mid Literacy,0.0,greater,250,0.188639,60.106417,0.0,3.801464,4,0.0
1,Answer_only_cleaned,Semantic_Loss,Low Literacy,0.0,greater,250,0.233637,65.975077,0.0,4.172630,4,0.0
2,Answer_only_cleaned,NLI_Entailment,Mid Literacy,1.0,less,250,0.461227,-45.634745,0.0,-2.886195,4,0.0
3,Answer_only_cleaned,NLI_Entailment,Low Literacy,1.0,less,250,0.401566,-55.756444,0.0,-3.526347,4,0.0
4,For_fine_tuning_cleaned,Semantic_Loss,Mid Literacy,0.0,greater,250,0.087213,35.127408,0.0,2.221652,4,0.0
5,For_fine_tuning_cleaned,Semantic_Loss,Low Literacy,0.0,greater,250,0.157832,41.755343,0.0,2.640840,4,0.0
6,For_fine_tuning_cleaned,NLI_Entailment,Mid Literacy,1.0,less,250,0.854210,-18.725896,0.0,-1.184330,4,0.0
7,For_fine_tuning_cleaned,NLI_Entailment,Low Literacy,1.0,less,250,0.681001,-23.789558,0.0,-1.504584,4,0.0

Repeated-measures ANOVA (topic = subject, literacy = within-subject factor)

,Text_Column,Metric,n,F,df1,df2,p,Partial_eta_squared,GG_epsilon,p_GG
0,Answer_only_cleaned,FK_Grade,250,6549.517806,2,498,0.0,0.963374,0.836704,0.0
1,Answer_only_cleaned,Word_Count,250,290.529397,2,498,0.0,0.538487,0.847836,0.0
2,Answer_only_cleaned,P_Comprehensive_Detailed,250,1133.248394,2,498,0.0,0.819859,0.978908,0.0
3,Answer_only_cleaned,P_Formal_Professional,250,782.915028,2,498,0.0,0.758701,0.938451,0.0
4,For_fine_tuning_cleaned,FK_Grade,250,1046.191214,2,498,0.0,0.807750,0.917835,0.0
5,For_fine_tuning_cleaned,Word_Count,250,689.393227,2,498,0.0,0.734653,0.883929,0.0
6,For_fine_tuning_cleaned,P_Comprehensive_Detailed,250,350.792877,2,498,0.0,0.584857,0.931720,0.0
7,For_fine_tuning_cleaned,P_Formal_Professional,250,85.454691,2,498,0.0,0.255505,0.682560,0.0

## Takeaways

Read the measured means and paired deltas above before drawing conclusions. Lower semantic loss and higher NLI entailment/ROUGE indicate stronger alignment with the within-topic High answer, while readability should remain appropriate for each literacy level. These metrics do not certify factual correctness. Pending entity counts mean the full paper-metric run is incomplete until the Gemini cell has been executed with credentials.